### ISSUE TITLE
Smoother Music Changer

### ISSUE THREAD

**Issue by Saphiria** [MinecraftFrontiers/Minecraft-Frontiers#10]
Would it be possible to make the music changing more subtle? It is a pain to get kicked just for music. I was being killed by a wolf and got kicked so it effected my battle. This also happened when I was fighting a player.

(credit me)

-------
When entering a predefined area for music loads, Minecraft will freeze display the loading screen until the audio has finished loading. Alternative could be asynchronous loading (credit ParinoriaComplex)

**Comment by endercrest** [comment]
This has been fixed for prototype phase 2
