### ISSUE TITLE
Metal mixer is broken (editted)

### ISSUE THREAD

**Issue by LeviathanSuperd** [MinecraftFrontiers/Minecraft-Frontiers#19]
I came on today and tried to use the metal mixer, it had 56 iron ore in it already and the metal former wouldn't work. Also the metal mixer still has issues and it loses iron ore sometimes, like when placed into the metal mixer it doesn't show up on the iron ore section and the ores are lost. 
 
(Editted)

**Comment by endercrest** [comment]
This should be fixed for prototype phase 2. Comment if it occurs again when phase 2 starts.
