### ISSUE TITLE
Splitting logs does not seem to work as explained in Wiki.

### ISSUE THREAD

**Issue by ZombieStriker** [MinecraftFrontiers/Minecraft-Frontiers#22]
While following the "Getting Started" wiki page, I managed to get stuck at "Splitting logs".  I am currently at [42,89,-300] where the blacksmith's tent is and I am clicking the stumps around the tent with the log in my hand. What is currently happening is when I place the block, the block disappears and goes back into my inventory. I am not sure if this is a bug, or if the wiki is not clear enough for me to understand what to do.

![2016-02-17_00 53 15](https://cloud.githubusercontent.com/assets/15203336/13101112/9a372b44-d511-11e5-82be-6108b7373726.png)
![2016-02-17_00 53 19](https://cloud.githubusercontent.com/assets/15203336/13101068/1ecc13c0-d511-11e5-81b9-c5c255375f85.png)
![2016-02-17_00 53 22](https://cloud.githubusercontent.com/assets/15203336/13101118/b0df34a4-d511-11e5-9f59-20139c0a6bcf.png)

**Comment by endercrest** [comment]
At this time you have to go to specific logs in the mining town. Near the other smelting station.
