### ISSUE TITLE
Vernos welcomes "null" to his shop.

### ISSUE THREAD

**Issue by ZombieStriker** [MinecraftFrontiers/Minecraft-Frontiers#23]
When saying "Hello" to Vernos, he will reply "Welcome to my humble shop,  null    ."  [89, 53, 232]
![2016-02-17_22 45 29](https://cloud.githubusercontent.com/assets/15203336/13133328/410b97b4-d5c8-11e5-822f-cf835b523d62.png)

**Comment by endercrest** [comment]
This has been fixed for prototype phase 2.
