### ISSUE TITLE
Strange Sword Breaking Behavior

### ISSUE THREAD

**Issue by Saphiria** [MinecraftFrontiers/Minecraft-Frontiers#3]
Sword will break if you attempt to attack with it after swinging at a block.

Replication Steps:
- Wield a sword (wooden sword)
- Attack the ground (The durability of the weapon will reduce to 2/60)
- Attack a player (I attacked Tom while he was in creative)
Result:
- The sword will break Clientside and will reappear a few seconds after at full durability once the client syncs with the server.

Possibly an issue while in combat

**Comment by endercrest** [comment]
Should now be fixed.
