### ISSUE TITLE
Potato Farm

### ISSUE THREAD

**Issue by Saphiria** [MinecraftFrontiers/Minecraft-Frontiers#7]
I just feel like the build quality for this doesn't meet up to the standard of MF. I mean, maybe make it look a little more abundant with a shed or something. Also maybe expand it.

![2016-01-01_16 48 04](https://cloud.githubusercontent.com/assets/12604271/12072511/7c7c2dea-b0a7-11e5-80cc-c91652fb3f73.png)

**Comment by endercrest** [comment]
This has been fixed for prototype phase 2
